global:
  catalog: bircatalog
  schema: pdf
  workspace_url: https://adb-984752964297111.11.azuredatabricks.net
  mlflow_experiment_name: pdf_exp

ingestion:
  source_volume_path: vol1/source
  entities_table: entities
  bronze_layer:
    metadata_extraction_llm: databricks-claude-haiku-4-5
    bronze_table: docs_bronze
  silver_layer:
    parsed_document_table: docs_silver_parsed_docs_raw
    document_elements_table: docs_silver_elements
    document_pages_table: docs_silver_pages
    image_output_path: vol1/parsed_doc_images
  gold_layer:
    aggregated_pages_table: docs_gold_pages
    page_quality_rater_llm: databricks-claude-sonnet-4
    page_quality_rater_prompt: |
      You are an expert and educator in the field of financial analysis and SEC documents. Below is an extract from an page extracted from an SEC filing. Evaluate whether the page has a high educational value and could be useful in generating an investment thesis and answering company-related questions. You should record your evaluation rating as a 1 if the page content is helpful or a 0 if the page contents is not helpful. Some guidelines for your scoring are provided below. \n\n
      * Any pages containing financial information, tables or metrics are considered helpful and should be given a 1\n
      * Any pages containing an overview of the company and/or its operations are considered helpful and should be given a 1\n
      * Any pages containing information about the company business model, risks, leadership, and management decisions are considered helpful and should be given a 1 \n
      * Any pages containing information about debts, securities, and issuances of any financial securities are considered helpful and should be given a 1\n
      * Agendas and key topics for the document are considered helpful and should be given a 1 \n
      * Title pages and tables of contents are considered not helpful and should be given a 0\n
      * RETURN THE SCORE (1 or 0) AND NOTHING ELSE\n

      The Extract can be found below:\n\n
  platinum_layer:
    summarization_llm: databricks-claude-sonnet-4
    # summarization_prompt: |
    #   The following document chunk was extracted from an SEC filing (10k, 8k, 10q, etc.).
    #   Summarize and situate the chunk in the larger context of an SEC doc. You should return a concise but descriptive summarization.
    #   Additionally, if the chunk contains any financial information, you should clearly highlight the financial metrics, data, and figures in the chunk.
    #   Any financial metrics should be reported in a structured, easily consumable format.
    #   Additionally, you should identify the SEC filing items and section that the chunk falls into, if possible, in your summarization.
    #   RETURN ONLY THE SUMMARIZATION AND NOTHING ELSE. Below is some additional information to aid in your summarization.
    summarization_prompt: |
      Summarize this chunk. You should return a concise summarization.
      RETURN ONLY THE SUMMARIZATION AND NOTHING ELSE.
    platinum_table: docs_platinum

  vector_search:
    endpoint_name: ka-f3925e58-vs-endpoint
    index_name: docs_platinum_index_bir
    primary_key: chunk_id
    embedding_source_column: page_content_final
    embedding_model_endpoint: databricks-gte-large-en
    pipeline_type: TRIGGERED
